spring.application.name=hackhub

spring.datasource.url=jdbc:h2:file:./src/data/hackhubDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Questa riga crea automaticamente le tabelle in base alle tue classi Entity
spring.jpa.hibernate.ddl-auto=update 
# Abilita la console H2 per vedere il DB su browser
spring.h2.console.enabled=true